package review

import (
	"path"
	"strings"
)

// DefaultExcludes are skipped unless the caller passes IncludeAll. These are
// paths where an AI reviewer reliably wastes budget: vendored or generated
// code, lockfiles, binaries, and build output.
func DefaultExcludes() []string {
	return []string{
		".git/**",
		// Both anchored and nested forms: a monorepo keeps vendored trees at
		// pkg/vendor or web/node_modules, and those were previously only
		// skipped by the directory walk — so diff- and worktree-scoped runs
		// still spent budget on them.
		"vendor/**", "**/vendor/**",
		"node_modules/**", "**/node_modules/**",
		"third_party/**", "**/third_party/**",
		"dist/**", "**/dist/**",
		"build/**", "**/build/**",
		"target/**",
		".venv/**", "**/.venv/**",
		"**/*.pb.go",
		"**/*_generated.go",
		"**/*.generated.*",
		"**/*.min.js",
		"**/*.min.css",
		"**/*.map",
		"**/*.snap",
		"**/go.sum",
		"**/package-lock.json",
		"**/pnpm-lock.yaml",
		"**/yarn.lock",
		"**/Cargo.lock",
		"**/poetry.lock",
		"**/composer.lock",
		"**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.ico",
		"**/*.pdf", "**/*.zip", "**/*.gz", "**/*.tar", "**/*.wasm",
		"**/*.mp3", "**/*.mp4", "**/*.woff", "**/*.woff2", "**/*.ttf",
	}
}

// generatedMarkers identify machine-written files whose content should not be
// reviewed even when the filename looks ordinary.
var generatedMarkers = []string{
	"code generated by",
	"@generated",
	"do not edit",
	"autogenerated by",
}

// LooksGenerated reports whether the head of a file marks it as generated.
// Only the first few lines are inspected, matching the Go convention.
func LooksGenerated(head string) bool {
	lines := strings.SplitN(head, "\n", 6)
	for i, ln := range lines {
		if i >= 5 {
			break
		}
		l := strings.ToLower(ln)
		for _, m := range generatedMarkers {
			if strings.Contains(l, m) {
				return true
			}
		}
	}
	return false
}

// MatchPattern reports whether a workspace-relative path matches a glob.
// Supported syntax: "*" and "?" within a segment, "**" across segments, a
// trailing "/" or bare directory name to match everything beneath it, and a
// pattern with no separator matching any path element's base name.
func MatchPattern(pattern, rel string) bool {
	pattern = strings.TrimSpace(strings.ReplaceAll(pattern, "\\", "/"))
	rel = strings.TrimPrefix(strings.ReplaceAll(rel, "\\", "/"), "./")
	if pattern == "" || rel == "" {
		return false
	}
	// "dir/" is shorthand for "dir/**".
	if strings.HasSuffix(pattern, "/") {
		pattern += "**"
	}
	// A bare name (no separator, no wildcard) matches the base name anywhere,
	// so `--exclude testdata` behaves the way users expect.
	if !strings.Contains(pattern, "/") && !strings.ContainsAny(pattern, "*?") {
		if pattern == path.Base(rel) {
			return true
		}
		return strings.HasPrefix(rel, pattern+"/") || strings.Contains(rel, "/"+pattern+"/")
	}
	if !strings.Contains(pattern, "/") {
		if ok, _ := path.Match(pattern, path.Base(rel)); ok {
			return true
		}
	}
	return matchSegments(strings.Split(pattern, "/"), strings.Split(rel, "/"))
}

// matchSegments implements "**"-aware glob matching over path segments.
func matchSegments(pat, seg []string) bool {
	for len(pat) > 0 {
		if pat[0] == "**" {
			// Trailing "**" matches one or more segments below the prefix, so
			// "internal/**" covers files under internal/ but not a file named
			// "internal" itself.
			if len(pat) == 1 {
				return len(seg) > 0
			}
			for i := 0; i <= len(seg); i++ {
				if matchSegments(pat[1:], seg[i:]) {
					return true
				}
			}
			return false
		}
		if len(seg) == 0 {
			return false
		}
		if ok, err := path.Match(pat[0], seg[0]); err != nil || !ok {
			return false
		}
		pat, seg = pat[1:], seg[1:]
	}
	return len(seg) == 0
}

// MatchAny reports whether rel matches any pattern, returning the one that hit.
func MatchAny(patterns []string, rel string) (string, bool) {
	for _, p := range patterns {
		if MatchPattern(p, rel) {
			return p, true
		}
	}
	return "", false
}
