package review

import (
	"context"
	"strings"
	"testing"
)

func TestGatherBudgetTruncatesByFileCount(t *testing.T) {
	names := []string{}
	files := map[string]string{}
	for _, n := range []string{"a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q"} {
		rel := "pkg/" + n + ".go"
		names = append(names, rel)
		files[rel] = "package p\n"
	}
	g := &fakeGit{repo: true, changed: names}
	sc, err := resolveScope(context.Background(), ScopeRequest{
		Workspace: "/ws", Diff: "main...HEAD", Budget: "small",
	}, g.run, memFS(files))
	if err != nil {
		t.Fatalf("resolve: %v", err)
	}
	small, _ := LookupBudget("small")
	if len(sc.Files) != small.MaxFiles {
		t.Fatalf("files = %d want %d", len(sc.Files), small.MaxFiles)
	}
	if !sc.Truncated || !strings.Contains(sc.TruncReason, "file limit") {
		t.Errorf("truncation not reported: %v %q", sc.Truncated, sc.TruncReason)
	}
	// Everything dropped must still be accounted for.
	if len(sc.Files)+len(sc.Excluded) != len(names) {
		t.Errorf("files+excluded = %d, want %d", len(sc.Files)+len(sc.Excluded), len(names))
	}
}

func TestGatherSkipsBinaryLargeAndGenerated(t *testing.T) {
	big := strings.Repeat("x", 50_000)
	files := map[string]string{
		"ok.go":        "package p\n",
		"binary.bin":   "abc\x00def",
		"huge.go":      big,
		"generated.go": "// Code generated by tool. DO NOT EDIT.\npackage p\n",
	}
	names := []string{"ok.go", "binary.bin", "huge.go", "generated.go"}
	g := &fakeGit{repo: true, changed: names}
	sc, err := resolveScope(context.Background(), ScopeRequest{
		Workspace: "/ws", Diff: "main...HEAD", Budget: "small",
	}, g.run, memFS(files))
	if err != nil {
		t.Fatalf("resolve: %v", err)
	}
	if len(sc.Files) != 1 || sc.Files[0].Path != "ok.go" {
		t.Fatalf("files = %v", sc.Paths())
	}
	reasons := map[string]string{}
	for _, e := range sc.Excluded {
		reasons[e.Path] = e.Reason
	}
	if !strings.Contains(reasons["binary.bin"], "binary") {
		t.Errorf("binary reason = %q", reasons["binary.bin"])
	}
	if !strings.Contains(reasons["huge.go"], "too large") {
		t.Errorf("large reason = %q", reasons["huge.go"])
	}
	if !strings.Contains(reasons["generated.go"], "generated") {
		t.Errorf("generated reason = %q", reasons["generated.go"])
	}
}

func TestGatherIncludeAllKeepsVendorAndGenerated(t *testing.T) {
	files := map[string]string{
		"vendor/x/y.go": "package x\n",
		"generated.go":  "// Code generated by tool. DO NOT EDIT.\npackage p\n",
	}
	g := &fakeGit{repo: true, changed: []string{"vendor/x/y.go", "generated.go"}}
	sc, err := resolveScope(context.Background(), ScopeRequest{
		Workspace: "/ws", Diff: "main...HEAD", IncludeAll: true,
	}, g.run, memFS(files))
	if err != nil {
		t.Fatalf("resolve: %v", err)
	}
	if len(sc.Files) != 2 {
		t.Fatalf("IncludeAll should keep everything: %v (excluded %+v)", sc.Paths(), sc.Excluded)
	}
}

func TestGatherUserExcludes(t *testing.T) {
	files := map[string]string{"internal/a.go": "package a\n", "internal/a_test.go": "package a\n"}
	g := &fakeGit{repo: true, changed: []string{"internal/a.go", "internal/a_test.go"}}
	sc, err := resolveScope(context.Background(), ScopeRequest{
		Workspace: "/ws", Diff: "main...HEAD", Excludes: []string{"**/*_test.go"},
	}, g.run, memFS(files))
	if err != nil {
		t.Fatalf("resolve: %v", err)
	}
	if len(sc.Files) != 1 || sc.Files[0].Path != "internal/a.go" {
		t.Fatalf("files = %v", sc.Paths())
	}
	if len(sc.Excluded) != 1 || !strings.Contains(sc.Excluded[0].Reason, "_test.go") {
		t.Errorf("exclusion not attributed to the user pattern: %+v", sc.Excluded)
	}
}

func TestScopeInfoProjection(t *testing.T) {
	g := &fakeGit{repo: true, changed: []string{"a.go", "vendor/b.go"}}
	req := ScopeRequest{Workspace: "/ws", Diff: "main...HEAD", Budget: "small"}
	sc, err := resolveScope(context.Background(), req, g.run,
		memFS(map[string]string{"a.go": "package a\n", "vendor/b.go": "package b\n"}))
	if err != nil {
		t.Fatalf("resolve: %v", err)
	}
	info := sc.Info(req)
	if info.FilesReviewed != 1 || info.FilesExcluded != 1 {
		t.Errorf("counts = %d/%d", info.FilesReviewed, info.FilesExcluded)
	}
	if info.Diff != "main...HEAD" || info.Budget != "small" {
		t.Errorf("info = %+v", info)
	}
	if len(info.Files) != 1 || info.Files[0] != "a.go" {
		t.Errorf("info.Files = %v", info.Files)
	}
}

// TestGatherUntrackedFilesGetContent guards a real bug: in worktree mode an
// untracked file has no diff against HEAD, so without a content fallback it
// consumed a scope slot while showing the model nothing.
func TestGatherUntrackedFilesGetContent(t *testing.T) {
	g := &fakeGit{repo: true, dirty: true, changed: []string{"tracked.go"}, untracked: []string{"brand_new.go"}}
	g.noDiffFor = map[string]bool{"brand_new.go": true}
	files := map[string]string{
		"tracked.go":   "package p\n\nfunc Old() {}\n",
		"brand_new.go": "package p\n\nfunc New() {}\n",
	}
	sc, err := resolveScope(context.Background(), ScopeRequest{Workspace: "/ws"}, g.run, memFS(files))
	if err != nil {
		t.Fatalf("resolve: %v", err)
	}
	var newFile *ScopeFile
	for i := range sc.Files {
		if sc.Files[i].Path == "brand_new.go" {
			newFile = &sc.Files[i]
		}
	}
	if newFile == nil {
		t.Fatalf("untracked file missing from scope: %v (excluded %+v)", sc.Paths(), sc.Excluded)
	}
	if newFile.Content == "" {
		t.Error("untracked file must carry full content when it has no diff")
	}
}

// TestGatherDropsFilesWithNothingToShow ensures a file we can neither diff nor
// read content for is excluded with a reason instead of padding the scope.
func TestGatherDropsFilesWithNothingToShow(t *testing.T) {
	g := &fakeGit{repo: true, changed: []string{"ghost.go"}}
	g.noDiffFor = map[string]bool{"ghost.go": true}
	sc, err := resolveScope(context.Background(), ScopeRequest{Workspace: "/ws", Diff: "main...HEAD"},
		g.run, memFS(map[string]string{"ghost.go": ""}))
	if err != nil {
		t.Fatalf("resolve: %v", err)
	}
	if len(sc.Files) != 0 {
		t.Fatalf("empty file should not occupy a scope slot: %v", sc.Paths())
	}
	if len(sc.Excluded) != 1 || !strings.Contains(sc.Excluded[0].Reason, "no diff or content") {
		t.Errorf("excluded = %+v", sc.Excluded)
	}
}

func TestScopeEmptyAndNilSafety(t *testing.T) {
	var sc *Scope
	if !sc.Empty() || sc.InScope("a.go") {
		t.Error("nil scope should be empty and match nothing")
	}
	if _, ok := sc.FileLines("a.go"); ok {
		t.Error("nil scope should report no file lines")
	}
	g := &fakeGit{repo: true, changed: nil}
	got, err := resolveScope(context.Background(), ScopeRequest{Workspace: "/ws", Diff: "main...HEAD"}, g.run, memFS(nil))
	if err != nil {
		t.Fatalf("resolve: %v", err)
	}
	if !got.Empty() {
		t.Errorf("scope with no changed files should be empty: %v", got.Paths())
	}
}
