package review

import "testing"

func TestMatchPattern(t *testing.T) {
	tests := []struct {
		pattern, rel string
		want         bool
	}{
		{"vendor/**", "vendor/x/y.go", true},
		{"vendor/**", "internal/vendor/x.go", false},
		{"**/*.pb.go", "api/v1/service.pb.go", true},
		{"**/*.pb.go", "api/service.go", false},
		{"*.md", "README.md", true},
		{"*.md", "docs/guide.md", true}, // bare pattern matches base name anywhere
		{"docs/*.md", "docs/guide.md", true},
		{"docs/*.md", "docs/sub/guide.md", false},
		{"docs/**/*.md", "docs/sub/deep/guide.md", true},
		{"testdata", "internal/testdata/fixture.json", true},
		{"testdata", "internal/testdata.go", false},
		{"build/", "build/out.js", true},
		{"**/go.sum", "go.sum", true},
		{"**/go.sum", "sub/mod/go.sum", true},
		{"internal/**", "internal/a/b/c.go", true},
		{"internal/**", "internal", false},
		{"", "a.go", false},
		{"*.go", "", false},
	}
	for _, tt := range tests {
		if got := MatchPattern(tt.pattern, tt.rel); got != tt.want {
			t.Errorf("MatchPattern(%q, %q) = %v want %v", tt.pattern, tt.rel, got, tt.want)
		}
	}
}

func TestMatchAny(t *testing.T) {
	pats := []string{"vendor/**", "**/*.min.js"}
	if p, ok := MatchAny(pats, "web/app.min.js"); !ok || p != "**/*.min.js" {
		t.Errorf("MatchAny = %q,%v", p, ok)
	}
	if _, ok := MatchAny(pats, "internal/api.go"); ok {
		t.Error("unexpected match")
	}
	if _, ok := MatchAny(nil, "a.go"); ok {
		t.Error("nil patterns should not match")
	}
}

func TestDefaultExcludesCoverUsualSuspects(t *testing.T) {
	ex := DefaultExcludes()
	for _, rel := range []string{
		"vendor/github.com/x/y.go", "node_modules/pkg/index.js", "go.sum",
		"package-lock.json", "api/v1/svc.pb.go", "assets/logo.png",
		".git/config", "web/bundle.min.js",
		".devenv/bin/mow", "nix/.devenv/state.txt", ".direnv/flake-profile",
		"crate/target/debug/foo", "__pycache__/a.pyc", "web/.next/cache",
		"coverage/lcov.info", "pkg/.cache/x",
	} {
		if _, ok := MatchAny(ex, rel); !ok {
			t.Errorf("default excludes miss %q", rel)
		}
	}
	for _, rel := range []string{"internal/api/users.go", "cmd/mow/main.go", "docs/harness.md"} {
		if p, ok := MatchAny(ex, rel); ok {
			t.Errorf("default excludes wrongly drop %q (pattern %q)", rel, p)
		}
	}
}

func TestLooksGenerated(t *testing.T) {
	yes := []string{
		"// Code generated by protoc-gen-go. DO NOT EDIT.\npackage x",
		"/* @generated */\nconst a = 1",
		"#!/bin/sh\n# autogenerated by tool\n",
	}
	for _, s := range yes {
		if !LooksGenerated(s) {
			t.Errorf("want generated: %q", s)
		}
	}
	no := []string{
		"package review\n\n// Validate normalizes findings.",
		"",
		"line1\nline2\nline3\nline4\nline5\nline6\n// Code generated by x", // too deep
	}
	for _, s := range no {
		if LooksGenerated(s) {
			t.Errorf("want NOT generated: %q", s)
		}
	}
}

func TestLookupBudget(t *testing.T) {
	if b, ok := LookupBudget(""); !ok || b.Name != "medium" {
		t.Errorf("empty budget = %+v,%v want medium", b, ok)
	}
	if b, ok := LookupBudget(" SMALL "); !ok || b.Name != "small" {
		t.Errorf("small budget = %+v,%v", b, ok)
	}
	if _, ok := LookupBudget("huge"); ok {
		t.Error("unknown budget should not resolve")
	}
	small, _ := LookupBudget("small")
	medium, _ := LookupBudget("medium")
	large, _ := LookupBudget("large")
	if !(small.MaxFiles < medium.MaxFiles && medium.MaxFiles < large.MaxFiles) {
		t.Error("budgets should grow monotonically")
	}
	if !(small.MaxTurns < medium.MaxTurns && medium.MaxTurns < large.MaxTurns) {
		t.Error("budget turn caps should grow monotonically")
	}
}

// Vendored trees are not always at the repo root. Before this, only the
// directory walk skipped a nested pkg/vendor — so diff- and worktree-scoped
// runs (which never walk) still spent budget reviewing dependencies.
func TestDefaultExcludesMatchNestedVendorTrees(t *testing.T) {
	ex := DefaultExcludes()
	shouldSkip := []string{
		"vendor/dep.go",
		"pkg/vendor/dep.go",
		"services/api/vendor/x/y.go",
		"node_modules/left-pad/index.js",
		"web/node_modules/left-pad/index.js",
		"internal/third_party/lib.go",
		"web/dist/bundle.js",
		".devenv/state.json",
		"pkg/.devenv/bin/x",
		"app/target/release/app",
		"src/__pycache__/mod.pyc",
		"web/.next/static/chunk.js",
		"frontend/coverage/lcov.info",
	}
	for _, p := range shouldSkip {
		if _, ok := MatchAny(ex, p); !ok {
			t.Errorf("%q should be excluded by default", p)
		}
	}
	// Real source that merely contains the words must survive.
	shouldKeep := []string{
		"vendors.go",
		"internal/vendoring/policy.go",
		"pkg/builder/build.go",
		"cmd/distribute/main.go",
		"coverage.go",
		"internal/targeting/plan.go",
	}
	for _, p := range shouldKeep {
		if pat, ok := MatchAny(ex, p); ok {
			t.Errorf("%q must not be excluded (matched %q)", p, pat)
		}
	}
}
